version: '3'
services:
  node-app:
    build:    # if you want to build docker file together with compose
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - PORT=3000
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=mypass
      - MONGO_IP=mongodb
      - MONGO_PORT=27017
    # env_file:
    #   - ./.env
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    env_file:
      - ./mongo.env
    volumes:
      - ./dbdata:/data/db
      # - mongo-db:/data/db

volumes:
  mongo-db:

